sonar.projectKey=SkyBooker_Frontend
sonar.projectName=SkyBooker Frontend
sonar.sources=src
sonar.host.url=http://localhost:9000
# Replace with your token from SonarQube!
sonar.login=sqa_cb06f325d0cecc9ba4b8e6b45e1079f3dd473a8f
sonar.javascript.lcov.reportPaths=coverage/lcov.info
